@baseUrl = http://localhost:3000

# RECADOS
###
GET {{baseUrl}}/recados/
?limit=20
&offset=20
###
GET {{baseUrl}}/recados/2
### CRIA UM RECADO
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "4 Novo Recado",
  "de": "joana",
  "para": "joao"
}
### ATUALIZA UM RECADO
PATCH  {{baseUrl}}/recados/2
Content-Type: application/json

{
  "texto": "ATUALIZAR é um recado de teste"
}
### APAGANDO UM RECADO
DELETE {{baseUrl}}/recados/2