@baseUrl = http://localhost:3000

# RECADOS
###
GET {{baseUrl}}/recados/
?limit=20
&offset=20
###
GET {{baseUrl}}/recados/2
### CRIA UM RECADO
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Novo recado",
  "de": "João",
  "para": "Maria",
  "lido": false,
  "data": "2026-06-02T11:22:55.830Z"
}
### ATUALIZA UM RECADO
PATCH  {{baseUrl}}/recados/2
Content-Type: application/json

{
  "texto": "ATUALIZAR é um recado de teste",
  "de": "João",
  "para": "Maria",
  "lido": false,
  "data": "2026-06-02T11:22:55.830Z"
}
### APAGANDO UM RECADO
DELETE {{baseUrl}}/recados/2