@baseUrl = http://localhost:3000

# RECADOS
###
GET {{baseUrl}}/recados/
?limit=20
&offset=20
###
GET {{baseUrl}}/recados/232132
### CRIA UM RECADO
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "recado": "Este é o recado que estou enviando",
  "nova-chave": "Outro valor"
}
### ATUALIZA UM RECADO
PATCH  {{baseUrl}}/recados/2
Content-Type: application/json

{
  "recado": "Este é o recado que estou enviando",
  "atualizar": true
}
### APAGANDO UM RECADO
DELETE {{baseUrl}}/recados/2